# Rosalind: Counting DNA Nucleotides
# 11/24/15

sample_text = "GCAAATGGTAATGTCGGAGATCCAGCCTTTCCGGCGAATTGTCACTTGCCCTATTGTAATCTAGATGAGGACATGTAATTGTGAGAGAGTAGCGTAGATTGCACGGGTCTAGTCCTTCATGATCTGGCTCAACTGAGGTGGTACGGCAAGTATTAAGCAAAAAGTATGAGGCCTAGAGGACTGAACTTTCTATGCAGAGGTAATTTTTTAGACTATCGGCAGGCACAGCAGCGCGAGACGTAGGGGAGCGGCTCGTTGCGTTTGGTGCTCAGAATGCCCCTTTACGACCGCCAAACTATCAGAAGGAGCTGTACGAATGGCCTAAGAGTGTTCAATGGGGGCGTAACCACAGGCGGCGTCATCAGTGTTTTAGAGCGGGTATGTTTAAGGCGGACACTGGGCGTCAGATGTTCTGAACGGCCTATACGGTTTTCGGGTTTTCGATACGGCGGGACCTCTTTCGTGAATCGAAGTATTACCCCGGACATGGCATCGAGGGCGCTTACTCAGTGGGAATGCGAGGATTTGTATTAGGGGAGTGTGCGGTACGACCTTCAGTTGCACCTTTCAGCCGTGGTAGGCAAACCCCACATGTTATTTACGAGGAATCTTGACATGCCACACACTAGCCTACCCATCGGAGGATATCGAGGCTTGTCCCACCGGAACCGTGCTCCACTCTCCATCTTCCCGTTAAAACGAGCTATTTTCACATAGTTCTGAAGCCTCACGCTTGGCTACTTTCTACAGATGTTTCTAGCCTCGCTGACGTTTATAAGGGTTTTCTAGACGTGAATATACAAAGGTGTATGTTATTTGCGTGGTCGCAACTAACGCGGTTTGGCGTATATGAGATAAACCACCCTTTAGCGATATCTCGGCAAAAACAGCGGCAGGTAAGTTATCTCGATATTCTCACTTCTTGAAAAATCCCCCACGTGTCCCGATGGAAGAACCCGATACGCAAGGAGGCAGCCGCGACCATTTATGAATGTTAC"

def count_nucleotides(dna):
	base_count = {"A":0, "C":0, "G":0, "T":0}
	for base in dna:
		if base == "A":
			base_count["A"] += 1
		elif base == "C":
			base_count["C"] += 1
		elif base == "G":
			base_count["G"] += 1
		elif base == "T":
			base_count["T"] += 1
		else:
			print "That's not a valid base."
	return base_count
	
test_dict = {"A":3, "C":2, "G":2, "T":2}

def test_the_thing(sample):
	if count_nucleotides(sample_text) == test_dict:
		print "works!"
	else:
		print "didn't work!"
		
dna_results = count_nucleotides(sample_text)

print dna_results["A"], dna_results["C"], dna_results["G"], dna_results["T"]
