# Rosalind: Counting DNA Nucleotides
# 11/24/15

dna_sample = "GATCGGGCACTTAGACTGGTCATACTATTATTGATAGAGGATGTGCGTCAGCCTACTTTTTTGCTGTACAGGAAGCGTAGAGTCGGCGTTATCCTGAAGTGGTCCAATTTCATCAGGCGTGATCGTCTTCCACAGACCTCGAGGACGCATTCGTAGTGGCGACTCATCCTTTTTCCCGGGCGGGGGGTTGGATGAGAGCAGAATCAGTCAATCGCACACGACCAAGGTACAACACCCCAAATACCGCCCTGCGGTAGGGGTTTCCCTTGGGCAAAGGTCACAGGGATTAAGACGACTTCCGGGTTCTGTTAGATATGGTCCAGAGCACGATACGTACGGTAGTTCTCTCTGGGAATATTTCAGCACCTGACCGTTAGTTTAAACAAATGCCCGATAGCCCTTCTGAACTACGGCCCGGGGCTTGCGAGTCGGCGGTCACTCCAGCATGAAACTAGGGAGTATGACACCCTGTCGACTTCTTACCCGAGAGACATCTTTGTAAGAACGGGGACCTATCACGCTGCAATGCCAATGGTTGTAACGGGACTTTACAATTTTTGGTGTGGTCTCATAGCCGGACTCTATCGCCTTGATCTGCTCCTCACGCAGAGATGGAATTAAACTGTGTTGAGACTACTCGAGGAATCGTGGCCTTAGCTACGCTCCCTTCTAACAGTGATATGACATTACAACAGCCACGGTATTCGGACACTTGCGCAGCTCTGGAACGGGGATTTATCGGGGGAGACGAGGTCTACATCATCAAATCTCTTTTCGCGCGGAATCTTCACGCCTAGTGTATTCTTTACCACTCTTAGGGTGCGCTCGGAACAGTGCGGGTGCAGGGGTGGTGGGTGGTCTGACCTTGATC"

sample_text = "AAAACCCGGT"

def flip_nucleotides(dna):
	complement_strand = ""
	for base in dna:
		if base == "A":
			complement_strand += "T"
		elif base == "T":
			complement_strand += "A"
		elif base == "C":
			complement_strand += "G"
		elif base == "G":
			complement_strand += "C"
		else:
			print "That's not a valid base."
	complement_strand = complement_strand[::-1]
	return complement_strand
	
test_strand = "ACCGGGTTTT"

def test_the_thing(sample):
	if flip_nucleotides(sample_text) == test_strand:
		print "works!"
	else:
		print "didn't work!"
	
#test_the_thing(test_strand)	

print flip_nucleotides(dna_sample)
